CREATE TABLE state
(
  id      INTEGER NOT NULL,
  name    CHARACTER VARYING(75) DEFAULT NULL :: CHARACTER VARYING,
  uf      CHARACTER VARYING(5) DEFAULT NULL :: CHARACTER VARYING,
  country INTEGER,
  CONSTRAINT state_pkey PRIMARY KEY (id),
  CONSTRAINT state_country_fkey FOREIGN KEY (country)
  REFERENCES country (id) MATCH SIMPLE
  ON UPDATE NO ACTION ON DELETE NO ACTION
);