CREATE TABLE city
(
  id    INTEGER NOT NULL,
  name  CHARACTER VARYING(120) DEFAULT NULL :: CHARACTER VARYING,
  state INTEGER NOT NULL,
  CONSTRAINT city_pkey PRIMARY KEY (id),
  CONSTRAINT city_state_fkey FOREIGN KEY (state)
  REFERENCES state (id) MATCH SIMPLE
  ON UPDATE NO ACTION ON DELETE NO ACTION
);