CREATE TABLE country
(
  id      INTEGER NOT NULL,
  name    CHARACTER VARYING(60) DEFAULT NULL :: CHARACTER VARYING,
  acronym CHARACTER VARYING(10) DEFAULT NULL :: CHARACTER VARYING,
  CONSTRAINT country_pkey PRIMARY KEY (id)
);